### ISSUE TITLE
cublas error

### ISSUE THREAD

**Issue by srikanthmalla** [enp1s0/cuMpSGEMM#1]
Hi @enp1s0 ,

Thank you for the amazing work! I am sure that this work will be very useful for many people in Machine Learning. I have successfully compiled the library and updated `LD_PRELOAD` and `LD_LIBRARY_PATH` with corresponding .so libraries mentioned in README.md and also the updated the `CUMPSGEMM_COMPUTE_MODE` environment variable to `TF32TC`. But when I run your `test/cupy/main.py` python example, I get this error:

```
Traceback (most recent call last):
  File "/mnt2/srikanth.m/cuMpSGEMM/test/cupy/main.py", line 21, in <module>
    dev_mat_C = cp.dot(dev_mat_A, dev_mat_B)
  File "/home/dgxadmin/anaconda3/envs/dl_env/lib/python3.10/site-packages/cupy/linalg/_product.py", line 65, in dot
    return a.dot(b, out)
  File "cupy/_core/core.pyx", line 1657, in cupy._core.core.ndarray.dot
  File "cupy/_core/_routines_linalg.pyx", line 430, in cupy._core._routines_linalg.dot
  File "cupy/_core/_routines_linalg.pyx", line 524, in cupy._core._routines_linalg.tensordot_core
  File "cupy/_core/_routines_linalg.pyx", line 659, in cupy._core._routines_linalg.tensordot_core_v11
  File "cupy_backends/cuda/libs/cublas.pyx", line 1328, in cupy_backends.cuda.libs.cublas.gemmEx
  File "cupy_backends/cuda/libs/cublas.pyx", line 396, in cupy_backends.cuda.libs.cublas.check_status
cupy_backends.cuda.libs.cublas.CUBLASError: CUBLAS_STATUS_EXECUTION_FAILED

```

without adding the compiled library binaries paths, `test/cupy/main.py`  is running properly (meaning no issue with CUBLAS installation on the server).

I wasn't sure if it is related to cupy, so I tried using different application library (pytorch), encountered same issue when using cuMpSGEMM:
```
    C_fp32 = torch.matmul(A, B)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Also, I am not sure if the README.md is outdated? because `ENABLE_A100_OPTIMAZED_PARAMETERS` is not found in `src/handle.cu` , but it is mentioned in README.md file.

Please let me know how to fix this issue.

Thank you,
Srikanth

**Comment by enp1s0** [comment]
Hi @srikanthmalla,

Thank you for opening the issue, and I'm sorry for the inconvenience.
I found that an error occurs when using the library with a recent version of CUDA, such as 12.8, specifically when calling an original cuBLAS GEMM function through this library.
The library calls an original cuBLAS GEMM function even if TF32TC etc is specified when the sizes of the input matrices are small ([the logic is here](https://github.com/enp1s0/cuMpSGEMM/blob/eaf08807c018b5cea196764c0a6e6fea83409d2d/src/default_cumpsgemm_rule.cu#L12-L14)).
So, can you try to run the cupy test again with larger input matrices by changing the following line and check if the error still occurs?
```diff
- for N in [2**log_N for log_N in range(5, 12)]:
+ for N in [2**log_N for log_N in range(11, 12)]:
```

Actually, I get an error, but it is not the same as yours. In my case, I get a segmentation fault message during the execution. So, I want to check if the situations are the same but only the error messages are different.

**Comment by srikanthmalla** [comment]
Hi @enp1s0 ,

Thanks for your time! I tried your suggestion, but got the same error CUBLAS_STATUS_EXECUTION_FAILED. This error occured on A100 dgx server, setup is with cuda 11.4 (and with cublas version: 11502).

So, I tried on different server, H100 hgx server, setup with cuda 12.4 (with cublas version: 120405). CUBLAS_STATUS_EXECUTION_FAILED error didn't occur, and memory gets allocated on GPU HBM memory (seems running). But only Segmentation fault message, similar to yours.

Best Regards,
Srikanth

**Comment by enp1s0** [comment]
Hi @srikanthmalla ,

I fixed the segmentation fault problem and it doesn't occur on my side now. Can you try the cupy test again with the latest main branch?

Thanks

**Comment by srikanthmalla** [comment]
Hi @enp1s0 ,

It works now! I tried the `test/cupy/main.py` on H100 hgx server, setup with cuda 12.4 (with cublas version: 120405) and below is the output:

```
python main.py
type = s , N = 32 , residual = 0.0 OK as FP32,  OK as FP16
type = s , N = 64 , residual = 0.0 OK as FP32,  OK as FP16
type = s , N = 128 , residual = 0.0 OK as FP32,  OK as FP16
type = s , N = 256 , residual = 2.3661335e-07 OK as FP32,  OK as FP16
type = s , N = 512 , residual = 1.7893002e-07 OK as FP32,  OK as FP16
type = s , N = 1024 , residual = 4.3308668e-07 OK as FP32,  OK as FP16
type = s , N = 2048 , residual = 2.1132796e-07 OK as FP32,  OK as FP16
type = c , N = 32 , residual = 1.017544e-07 OK as FP32,  OK as FP16
type = c , N = 64 , residual = 1.3302862e-07 OK as FP32,  OK as FP16
type = c , N = 128 , residual = 2.8795213e-07 OK as FP32,  OK as FP16
type = c , N = 256 , residual = 1.3570667e-07 OK as FP32,  OK as FP16
type = c , N = 512 , residual = 4.523881e-07 OK as FP32,  OK as FP16
type = c , N = 1024 , residual = 6.106878e-07 OK as FP32,  OK as FP16
type = c , N = 2048 , residual = 1.2107884e-07 OK as FP32,  OK as FP16
```

We can close this issue. Thank you!

**Comment by enp1s0** [comment]
Hi @srikanthmalla ,

Thank you for checking the bug fix.
Let me know if you have any other problems!
